package cn.openlo.tutorial.dto;

import java.io.Serializable;
import java.math.BigDecimal;

public class LoTutorialCustShare extends LoTutorialCustShareKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_cust_share.real_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private BigDecimal realShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_cust_share.pre_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private BigDecimal preShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lo_tutorial_cust_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_cust_share.real_share
     *
     * @return the value of lo_tutorial_cust_share.real_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public BigDecimal getRealShare() {
        return realShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_cust_share.real_share
     *
     * @param realShare the value for lo_tutorial_cust_share.real_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setRealShare(BigDecimal realShare) {
        this.realShare = realShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_cust_share.pre_share
     *
     * @return the value of lo_tutorial_cust_share.pre_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public BigDecimal getPreShare() {
        return preShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_cust_share.pre_share
     *
     * @param preShare the value for lo_tutorial_cust_share.pre_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setPreShare(BigDecimal preShare) {
        this.preShare = preShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_cust_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", realShare=").append(realShare);
        sb.append(", preShare=").append(preShare);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}