package cn.openlo.tutorial.dto;

import cn.openlo.datasource.executor.ShardingExample;
import cn.openlo.datasource.executor.ShardingTable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LoTutorialOrderCriteria implements ShardingTable, ShardingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    protected List<Criteria> oredCriteria;

    protected Integer limit;

    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    protected String dbGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    protected String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    protected String tableIndex;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public LoTutorialOrderCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return this.limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return this.offset;
    }

    public BoundBuilder boundBuilder() {
        return new BoundBuilder();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setDbGroup(String dbGroup) {
        this.dbGroup = dbGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getDbGroup() {
        return dbGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setTableIndex(String tableIndex) {
        this.tableIndex = tableIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getTableIndex() {
        return tableIndex;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("order_no is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("order_no is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("order_no =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("order_no <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("order_no >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("order_no >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(String value) {
            addCriterion("order_no <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("order_no <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLike(String value) {
            addCriterion("order_no like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotLike(String value) {
            addCriterion("order_no not like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("order_no in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("order_no not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("order_no between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("order_no not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andChannelIsNull() {
            addCriterion("channel is null");
            return (Criteria) this;
        }

        public Criteria andChannelIsNotNull() {
            addCriterion("channel is not null");
            return (Criteria) this;
        }

        public Criteria andChannelEqualTo(String value) {
            addCriterion("channel =", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotEqualTo(String value) {
            addCriterion("channel <>", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThan(String value) {
            addCriterion("channel >", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThanOrEqualTo(String value) {
            addCriterion("channel >=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThan(String value) {
            addCriterion("channel <", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThanOrEqualTo(String value) {
            addCriterion("channel <=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLike(String value) {
            addCriterion("channel like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotLike(String value) {
            addCriterion("channel not like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelIn(List<String> values) {
            addCriterion("channel in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotIn(List<String> values) {
            addCriterion("channel not in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelBetween(String value1, String value2) {
            addCriterion("channel between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotBetween(String value1, String value2) {
            addCriterion("channel not between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelDateIsNull() {
            addCriterion("channel_date is null");
            return (Criteria) this;
        }

        public Criteria andChannelDateIsNotNull() {
            addCriterion("channel_date is not null");
            return (Criteria) this;
        }

        public Criteria andChannelDateEqualTo(String value) {
            addCriterion("channel_date =", value, "channelDate");
            return (Criteria) this;
        }

        public Criteria andChannelDateNotEqualTo(String value) {
            addCriterion("channel_date <>", value, "channelDate");
            return (Criteria) this;
        }

        public Criteria andChannelDateGreaterThan(String value) {
            addCriterion("channel_date >", value, "channelDate");
            return (Criteria) this;
        }

        public Criteria andChannelDateGreaterThanOrEqualTo(String value) {
            addCriterion("channel_date >=", value, "channelDate");
            return (Criteria) this;
        }

        public Criteria andChannelDateLessThan(String value) {
            addCriterion("channel_date <", value, "channelDate");
            return (Criteria) this;
        }

        public Criteria andChannelDateLessThanOrEqualTo(String value) {
            addCriterion("channel_date <=", value, "channelDate");
            return (Criteria) this;
        }

        public Criteria andChannelDateLike(String value) {
            addCriterion("channel_date like", value, "channelDate");
            return (Criteria) this;
        }

        public Criteria andChannelDateNotLike(String value) {
            addCriterion("channel_date not like", value, "channelDate");
            return (Criteria) this;
        }

        public Criteria andChannelDateIn(List<String> values) {
            addCriterion("channel_date in", values, "channelDate");
            return (Criteria) this;
        }

        public Criteria andChannelDateNotIn(List<String> values) {
            addCriterion("channel_date not in", values, "channelDate");
            return (Criteria) this;
        }

        public Criteria andChannelDateBetween(String value1, String value2) {
            addCriterion("channel_date between", value1, value2, "channelDate");
            return (Criteria) this;
        }

        public Criteria andChannelDateNotBetween(String value1, String value2) {
            addCriterion("channel_date not between", value1, value2, "channelDate");
            return (Criteria) this;
        }

        public Criteria andChannelJnlNoIsNull() {
            addCriterion("channel_jnl_no is null");
            return (Criteria) this;
        }

        public Criteria andChannelJnlNoIsNotNull() {
            addCriterion("channel_jnl_no is not null");
            return (Criteria) this;
        }

        public Criteria andChannelJnlNoEqualTo(String value) {
            addCriterion("channel_jnl_no =", value, "channelJnlNo");
            return (Criteria) this;
        }

        public Criteria andChannelJnlNoNotEqualTo(String value) {
            addCriterion("channel_jnl_no <>", value, "channelJnlNo");
            return (Criteria) this;
        }

        public Criteria andChannelJnlNoGreaterThan(String value) {
            addCriterion("channel_jnl_no >", value, "channelJnlNo");
            return (Criteria) this;
        }

        public Criteria andChannelJnlNoGreaterThanOrEqualTo(String value) {
            addCriterion("channel_jnl_no >=", value, "channelJnlNo");
            return (Criteria) this;
        }

        public Criteria andChannelJnlNoLessThan(String value) {
            addCriterion("channel_jnl_no <", value, "channelJnlNo");
            return (Criteria) this;
        }

        public Criteria andChannelJnlNoLessThanOrEqualTo(String value) {
            addCriterion("channel_jnl_no <=", value, "channelJnlNo");
            return (Criteria) this;
        }

        public Criteria andChannelJnlNoLike(String value) {
            addCriterion("channel_jnl_no like", value, "channelJnlNo");
            return (Criteria) this;
        }

        public Criteria andChannelJnlNoNotLike(String value) {
            addCriterion("channel_jnl_no not like", value, "channelJnlNo");
            return (Criteria) this;
        }

        public Criteria andChannelJnlNoIn(List<String> values) {
            addCriterion("channel_jnl_no in", values, "channelJnlNo");
            return (Criteria) this;
        }

        public Criteria andChannelJnlNoNotIn(List<String> values) {
            addCriterion("channel_jnl_no not in", values, "channelJnlNo");
            return (Criteria) this;
        }

        public Criteria andChannelJnlNoBetween(String value1, String value2) {
            addCriterion("channel_jnl_no between", value1, value2, "channelJnlNo");
            return (Criteria) this;
        }

        public Criteria andChannelJnlNoNotBetween(String value1, String value2) {
            addCriterion("channel_jnl_no not between", value1, value2, "channelJnlNo");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNull() {
            addCriterion("product_code is null");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNotNull() {
            addCriterion("product_code is not null");
            return (Criteria) this;
        }

        public Criteria andProductCodeEqualTo(String value) {
            addCriterion("product_code =", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotEqualTo(String value) {
            addCriterion("product_code <>", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThan(String value) {
            addCriterion("product_code >", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThanOrEqualTo(String value) {
            addCriterion("product_code >=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThan(String value) {
            addCriterion("product_code <", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThanOrEqualTo(String value) {
            addCriterion("product_code <=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLike(String value) {
            addCriterion("product_code like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotLike(String value) {
            addCriterion("product_code not like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeIn(List<String> values) {
            addCriterion("product_code in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotIn(List<String> values) {
            addCriterion("product_code not in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeBetween(String value1, String value2) {
            addCriterion("product_code between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotBetween(String value1, String value2) {
            addCriterion("product_code not between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andTransActionIsNull() {
            addCriterion("trans_action is null");
            return (Criteria) this;
        }

        public Criteria andTransActionIsNotNull() {
            addCriterion("trans_action is not null");
            return (Criteria) this;
        }

        public Criteria andTransActionEqualTo(String value) {
            addCriterion("trans_action =", value, "transAction");
            return (Criteria) this;
        }

        public Criteria andTransActionNotEqualTo(String value) {
            addCriterion("trans_action <>", value, "transAction");
            return (Criteria) this;
        }

        public Criteria andTransActionGreaterThan(String value) {
            addCriterion("trans_action >", value, "transAction");
            return (Criteria) this;
        }

        public Criteria andTransActionGreaterThanOrEqualTo(String value) {
            addCriterion("trans_action >=", value, "transAction");
            return (Criteria) this;
        }

        public Criteria andTransActionLessThan(String value) {
            addCriterion("trans_action <", value, "transAction");
            return (Criteria) this;
        }

        public Criteria andTransActionLessThanOrEqualTo(String value) {
            addCriterion("trans_action <=", value, "transAction");
            return (Criteria) this;
        }

        public Criteria andTransActionLike(String value) {
            addCriterion("trans_action like", value, "transAction");
            return (Criteria) this;
        }

        public Criteria andTransActionNotLike(String value) {
            addCriterion("trans_action not like", value, "transAction");
            return (Criteria) this;
        }

        public Criteria andTransActionIn(List<String> values) {
            addCriterion("trans_action in", values, "transAction");
            return (Criteria) this;
        }

        public Criteria andTransActionNotIn(List<String> values) {
            addCriterion("trans_action not in", values, "transAction");
            return (Criteria) this;
        }

        public Criteria andTransActionBetween(String value1, String value2) {
            addCriterion("trans_action between", value1, value2, "transAction");
            return (Criteria) this;
        }

        public Criteria andTransActionNotBetween(String value1, String value2) {
            addCriterion("trans_action not between", value1, value2, "transAction");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNull() {
            addCriterion("cust_id is null");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNotNull() {
            addCriterion("cust_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustIdEqualTo(String value) {
            addCriterion("cust_id =", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotEqualTo(String value) {
            addCriterion("cust_id <>", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThan(String value) {
            addCriterion("cust_id >", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThanOrEqualTo(String value) {
            addCriterion("cust_id >=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThan(String value) {
            addCriterion("cust_id <", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThanOrEqualTo(String value) {
            addCriterion("cust_id <=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLike(String value) {
            addCriterion("cust_id like", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotLike(String value) {
            addCriterion("cust_id not like", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdIn(List<String> values) {
            addCriterion("cust_id in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotIn(List<String> values) {
            addCriterion("cust_id not in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdBetween(String value1, String value2) {
            addCriterion("cust_id between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotBetween(String value1, String value2) {
            addCriterion("cust_id not between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNull() {
            addCriterion("cust_name is null");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNotNull() {
            addCriterion("cust_name is not null");
            return (Criteria) this;
        }

        public Criteria andCustNameEqualTo(String value) {
            addCriterion("cust_name =", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotEqualTo(String value) {
            addCriterion("cust_name <>", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThan(String value) {
            addCriterion("cust_name >", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThanOrEqualTo(String value) {
            addCriterion("cust_name >=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThan(String value) {
            addCriterion("cust_name <", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThanOrEqualTo(String value) {
            addCriterion("cust_name <=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLike(String value) {
            addCriterion("cust_name like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotLike(String value) {
            addCriterion("cust_name not like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameIn(List<String> values) {
            addCriterion("cust_name in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotIn(List<String> values) {
            addCriterion("cust_name not in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameBetween(String value1, String value2) {
            addCriterion("cust_name between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotBetween(String value1, String value2) {
            addCriterion("cust_name not between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(String value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(String value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(String value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(String value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(String value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLike(String value) {
            addCriterion("product_id like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotLike(String value) {
            addCriterion("product_id not like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<String> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<String> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(String value1, String value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(String value1, String value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andApplyAmountIsNull() {
            addCriterion("apply_amount is null");
            return (Criteria) this;
        }

        public Criteria andApplyAmountIsNotNull() {
            addCriterion("apply_amount is not null");
            return (Criteria) this;
        }

        public Criteria andApplyAmountEqualTo(BigDecimal value) {
            addCriterion("apply_amount =", value, "applyAmount");
            return (Criteria) this;
        }

        public Criteria andApplyAmountNotEqualTo(BigDecimal value) {
            addCriterion("apply_amount <>", value, "applyAmount");
            return (Criteria) this;
        }

        public Criteria andApplyAmountGreaterThan(BigDecimal value) {
            addCriterion("apply_amount >", value, "applyAmount");
            return (Criteria) this;
        }

        public Criteria andApplyAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("apply_amount >=", value, "applyAmount");
            return (Criteria) this;
        }

        public Criteria andApplyAmountLessThan(BigDecimal value) {
            addCriterion("apply_amount <", value, "applyAmount");
            return (Criteria) this;
        }

        public Criteria andApplyAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("apply_amount <=", value, "applyAmount");
            return (Criteria) this;
        }

        public Criteria andApplyAmountIn(List<BigDecimal> values) {
            addCriterion("apply_amount in", values, "applyAmount");
            return (Criteria) this;
        }

        public Criteria andApplyAmountNotIn(List<BigDecimal> values) {
            addCriterion("apply_amount not in", values, "applyAmount");
            return (Criteria) this;
        }

        public Criteria andApplyAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("apply_amount between", value1, value2, "applyAmount");
            return (Criteria) this;
        }

        public Criteria andApplyAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("apply_amount not between", value1, value2, "applyAmount");
            return (Criteria) this;
        }

        public Criteria andApplyShareIsNull() {
            addCriterion("apply_share is null");
            return (Criteria) this;
        }

        public Criteria andApplyShareIsNotNull() {
            addCriterion("apply_share is not null");
            return (Criteria) this;
        }

        public Criteria andApplyShareEqualTo(BigDecimal value) {
            addCriterion("apply_share =", value, "applyShare");
            return (Criteria) this;
        }

        public Criteria andApplyShareNotEqualTo(BigDecimal value) {
            addCriterion("apply_share <>", value, "applyShare");
            return (Criteria) this;
        }

        public Criteria andApplyShareGreaterThan(BigDecimal value) {
            addCriterion("apply_share >", value, "applyShare");
            return (Criteria) this;
        }

        public Criteria andApplyShareGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("apply_share >=", value, "applyShare");
            return (Criteria) this;
        }

        public Criteria andApplyShareLessThan(BigDecimal value) {
            addCriterion("apply_share <", value, "applyShare");
            return (Criteria) this;
        }

        public Criteria andApplyShareLessThanOrEqualTo(BigDecimal value) {
            addCriterion("apply_share <=", value, "applyShare");
            return (Criteria) this;
        }

        public Criteria andApplyShareIn(List<BigDecimal> values) {
            addCriterion("apply_share in", values, "applyShare");
            return (Criteria) this;
        }

        public Criteria andApplyShareNotIn(List<BigDecimal> values) {
            addCriterion("apply_share not in", values, "applyShare");
            return (Criteria) this;
        }

        public Criteria andApplyShareBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("apply_share between", value1, value2, "applyShare");
            return (Criteria) this;
        }

        public Criteria andApplyShareNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("apply_share not between", value1, value2, "applyShare");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountIsNull() {
            addCriterion("confirm_amount is null");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountIsNotNull() {
            addCriterion("confirm_amount is not null");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountEqualTo(BigDecimal value) {
            addCriterion("confirm_amount =", value, "confirmAmount");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountNotEqualTo(BigDecimal value) {
            addCriterion("confirm_amount <>", value, "confirmAmount");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountGreaterThan(BigDecimal value) {
            addCriterion("confirm_amount >", value, "confirmAmount");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("confirm_amount >=", value, "confirmAmount");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountLessThan(BigDecimal value) {
            addCriterion("confirm_amount <", value, "confirmAmount");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("confirm_amount <=", value, "confirmAmount");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountIn(List<BigDecimal> values) {
            addCriterion("confirm_amount in", values, "confirmAmount");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountNotIn(List<BigDecimal> values) {
            addCriterion("confirm_amount not in", values, "confirmAmount");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("confirm_amount between", value1, value2, "confirmAmount");
            return (Criteria) this;
        }

        public Criteria andConfirmAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("confirm_amount not between", value1, value2, "confirmAmount");
            return (Criteria) this;
        }

        public Criteria andConfirmShareIsNull() {
            addCriterion("confirm_share is null");
            return (Criteria) this;
        }

        public Criteria andConfirmShareIsNotNull() {
            addCriterion("confirm_share is not null");
            return (Criteria) this;
        }

        public Criteria andConfirmShareEqualTo(BigDecimal value) {
            addCriterion("confirm_share =", value, "confirmShare");
            return (Criteria) this;
        }

        public Criteria andConfirmShareNotEqualTo(BigDecimal value) {
            addCriterion("confirm_share <>", value, "confirmShare");
            return (Criteria) this;
        }

        public Criteria andConfirmShareGreaterThan(BigDecimal value) {
            addCriterion("confirm_share >", value, "confirmShare");
            return (Criteria) this;
        }

        public Criteria andConfirmShareGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("confirm_share >=", value, "confirmShare");
            return (Criteria) this;
        }

        public Criteria andConfirmShareLessThan(BigDecimal value) {
            addCriterion("confirm_share <", value, "confirmShare");
            return (Criteria) this;
        }

        public Criteria andConfirmShareLessThanOrEqualTo(BigDecimal value) {
            addCriterion("confirm_share <=", value, "confirmShare");
            return (Criteria) this;
        }

        public Criteria andConfirmShareIn(List<BigDecimal> values) {
            addCriterion("confirm_share in", values, "confirmShare");
            return (Criteria) this;
        }

        public Criteria andConfirmShareNotIn(List<BigDecimal> values) {
            addCriterion("confirm_share not in", values, "confirmShare");
            return (Criteria) this;
        }

        public Criteria andConfirmShareBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("confirm_share between", value1, value2, "confirmShare");
            return (Criteria) this;
        }

        public Criteria andConfirmShareNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("confirm_share not between", value1, value2, "confirmShare");
            return (Criteria) this;
        }

        public Criteria andContractNoIsNull() {
            addCriterion("contract_no is null");
            return (Criteria) this;
        }

        public Criteria andContractNoIsNotNull() {
            addCriterion("contract_no is not null");
            return (Criteria) this;
        }

        public Criteria andContractNoEqualTo(String value) {
            addCriterion("contract_no =", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoNotEqualTo(String value) {
            addCriterion("contract_no <>", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoGreaterThan(String value) {
            addCriterion("contract_no >", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoGreaterThanOrEqualTo(String value) {
            addCriterion("contract_no >=", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoLessThan(String value) {
            addCriterion("contract_no <", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoLessThanOrEqualTo(String value) {
            addCriterion("contract_no <=", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoLike(String value) {
            addCriterion("contract_no like", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoNotLike(String value) {
            addCriterion("contract_no not like", value, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoIn(List<String> values) {
            addCriterion("contract_no in", values, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoNotIn(List<String> values) {
            addCriterion("contract_no not in", values, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoBetween(String value1, String value2) {
            addCriterion("contract_no between", value1, value2, "contractNo");
            return (Criteria) this;
        }

        public Criteria andContractNoNotBetween(String value1, String value2) {
            addCriterion("contract_no not between", value1, value2, "contractNo");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNull() {
            addCriterion("order_status is null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNotNull() {
            addCriterion("order_status is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusEqualTo(String value) {
            addCriterion("order_status =", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotEqualTo(String value) {
            addCriterion("order_status <>", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThan(String value) {
            addCriterion("order_status >", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThanOrEqualTo(String value) {
            addCriterion("order_status >=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThan(String value) {
            addCriterion("order_status <", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThanOrEqualTo(String value) {
            addCriterion("order_status <=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLike(String value) {
            addCriterion("order_status like", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotLike(String value) {
            addCriterion("order_status not like", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIn(List<String> values) {
            addCriterion("order_status in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotIn(List<String> values) {
            addCriterion("order_status not in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusBetween(String value1, String value2) {
            addCriterion("order_status between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotBetween(String value1, String value2) {
            addCriterion("order_status not between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusIsNull() {
            addCriterion("handle_status is null");
            return (Criteria) this;
        }

        public Criteria andHandleStatusIsNotNull() {
            addCriterion("handle_status is not null");
            return (Criteria) this;
        }

        public Criteria andHandleStatusEqualTo(String value) {
            addCriterion("handle_status =", value, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusNotEqualTo(String value) {
            addCriterion("handle_status <>", value, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusGreaterThan(String value) {
            addCriterion("handle_status >", value, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusGreaterThanOrEqualTo(String value) {
            addCriterion("handle_status >=", value, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusLessThan(String value) {
            addCriterion("handle_status <", value, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusLessThanOrEqualTo(String value) {
            addCriterion("handle_status <=", value, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusLike(String value) {
            addCriterion("handle_status like", value, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusNotLike(String value) {
            addCriterion("handle_status not like", value, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusIn(List<String> values) {
            addCriterion("handle_status in", values, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusNotIn(List<String> values) {
            addCriterion("handle_status not in", values, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusBetween(String value1, String value2) {
            addCriterion("handle_status between", value1, value2, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andHandleStatusNotBetween(String value1, String value2) {
            addCriterion("handle_status not between", value1, value2, "handleStatus");
            return (Criteria) this;
        }

        public Criteria andExtDataIsNull() {
            addCriterion("ext_data is null");
            return (Criteria) this;
        }

        public Criteria andExtDataIsNotNull() {
            addCriterion("ext_data is not null");
            return (Criteria) this;
        }

        public Criteria andExtDataEqualTo(String value) {
            addCriterion("ext_data =", value, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataNotEqualTo(String value) {
            addCriterion("ext_data <>", value, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataGreaterThan(String value) {
            addCriterion("ext_data >", value, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataGreaterThanOrEqualTo(String value) {
            addCriterion("ext_data >=", value, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataLessThan(String value) {
            addCriterion("ext_data <", value, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataLessThanOrEqualTo(String value) {
            addCriterion("ext_data <=", value, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataLike(String value) {
            addCriterion("ext_data like", value, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataNotLike(String value) {
            addCriterion("ext_data not like", value, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataIn(List<String> values) {
            addCriterion("ext_data in", values, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataNotIn(List<String> values) {
            addCriterion("ext_data not in", values, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataBetween(String value1, String value2) {
            addCriterion("ext_data between", value1, value2, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataNotBetween(String value1, String value2) {
            addCriterion("ext_data not between", value1, value2, "extData");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("created_by like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("created_by not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andDateCreatedIsNull() {
            addCriterion("date_created is null");
            return (Criteria) this;
        }

        public Criteria andDateCreatedIsNotNull() {
            addCriterion("date_created is not null");
            return (Criteria) this;
        }

        public Criteria andDateCreatedEqualTo(Date value) {
            addCriterion("date_created =", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedNotEqualTo(Date value) {
            addCriterion("date_created <>", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedGreaterThan(Date value) {
            addCriterion("date_created >", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("date_created >=", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedLessThan(Date value) {
            addCriterion("date_created <", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedLessThanOrEqualTo(Date value) {
            addCriterion("date_created <=", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedIn(List<Date> values) {
            addCriterion("date_created in", values, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedNotIn(List<Date> values) {
            addCriterion("date_created not in", values, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedBetween(Date value1, Date value2) {
            addCriterion("date_created between", value1, value2, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedNotBetween(Date value1, Date value2) {
            addCriterion("date_created not between", value1, value2, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNull() {
            addCriterion("updated_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNotNull() {
            addCriterion("updated_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByEqualTo(String value) {
            addCriterion("updated_by =", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotEqualTo(String value) {
            addCriterion("updated_by <>", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThan(String value) {
            addCriterion("updated_by >", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThanOrEqualTo(String value) {
            addCriterion("updated_by >=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThan(String value) {
            addCriterion("updated_by <", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThanOrEqualTo(String value) {
            addCriterion("updated_by <=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLike(String value) {
            addCriterion("updated_by like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotLike(String value) {
            addCriterion("updated_by not like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIn(List<String> values) {
            addCriterion("updated_by in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotIn(List<String> values) {
            addCriterion("updated_by not in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByBetween(String value1, String value2) {
            addCriterion("updated_by between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotBetween(String value1, String value2) {
            addCriterion("updated_by not between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedIsNull() {
            addCriterion("date_updated is null");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedIsNotNull() {
            addCriterion("date_updated is not null");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedEqualTo(Date value) {
            addCriterion("date_updated =", value, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedNotEqualTo(Date value) {
            addCriterion("date_updated <>", value, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedGreaterThan(Date value) {
            addCriterion("date_updated >", value, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedGreaterThanOrEqualTo(Date value) {
            addCriterion("date_updated >=", value, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedLessThan(Date value) {
            addCriterion("date_updated <", value, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedLessThanOrEqualTo(Date value) {
            addCriterion("date_updated <=", value, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedIn(List<Date> values) {
            addCriterion("date_updated in", values, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedNotIn(List<Date> values) {
            addCriterion("date_updated not in", values, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedBetween(Date value1, Date value2) {
            addCriterion("date_updated between", value1, value2, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedNotBetween(Date value1, Date value2) {
            addCriterion("date_updated not between", value1, value2, "dateUpdated");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public class BoundBuilder {
        protected Integer limit;

        protected Integer offset;

        public Integer limit() {
            return this.limit;
        }

        public BoundBuilder limit(Integer limit) {
            this.limit = limit;
            return this;
        }

        public Integer offset() {
            return this.offset;
        }

        public BoundBuilder offset(Integer offset) {
            this.offset = offset;
            return this;
        }

        public LoTutorialOrderCriteria build() {
            LoTutorialOrderCriteria.this.limit = limit;
            LoTutorialOrderCriteria.this.offset = offset;
            return LoTutorialOrderCriteria.this;
        }
    }
}