package cn.openlo.tutorial.dto;

import cn.openlo.gear.dataobject.PersistentDTOSupport;
import java.io.Serializable;
import java.math.BigDecimal;

public class LoTutorialOrder extends PersistentDTOSupport implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_order.order_no
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_order.channel
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_order.channel_date
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private String channelDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_order.channel_jnl_no
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private String channelJnlNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_order.product_code
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_order.trans_action
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private String transAction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_order.cust_id
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private String custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_order.cust_name
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_order.product_id
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_order.product_name
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_order.apply_amount
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private BigDecimal applyAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_order.apply_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private BigDecimal applyShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_order.confirm_amount
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private BigDecimal confirmAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_order.confirm_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private BigDecimal confirmShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_order.contract_no
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private String contractNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_order.order_status
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_order.handle_status
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private String handleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_order.ext_data
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private String extData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_order.order_no
     *
     * @return the value of lo_tutorial_order.order_no
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_order.order_no
     *
     * @param orderNo the value for lo_tutorial_order.order_no
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_order.channel
     *
     * @return the value of lo_tutorial_order.channel
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_order.channel
     *
     * @param channel the value for lo_tutorial_order.channel
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_order.channel_date
     *
     * @return the value of lo_tutorial_order.channel_date
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getChannelDate() {
        return channelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_order.channel_date
     *
     * @param channelDate the value for lo_tutorial_order.channel_date
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setChannelDate(String channelDate) {
        this.channelDate = channelDate == null ? null : channelDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_order.channel_jnl_no
     *
     * @return the value of lo_tutorial_order.channel_jnl_no
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getChannelJnlNo() {
        return channelJnlNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_order.channel_jnl_no
     *
     * @param channelJnlNo the value for lo_tutorial_order.channel_jnl_no
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setChannelJnlNo(String channelJnlNo) {
        this.channelJnlNo = channelJnlNo == null ? null : channelJnlNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_order.product_code
     *
     * @return the value of lo_tutorial_order.product_code
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_order.product_code
     *
     * @param productCode the value for lo_tutorial_order.product_code
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_order.trans_action
     *
     * @return the value of lo_tutorial_order.trans_action
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getTransAction() {
        return transAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_order.trans_action
     *
     * @param transAction the value for lo_tutorial_order.trans_action
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setTransAction(String transAction) {
        this.transAction = transAction == null ? null : transAction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_order.cust_id
     *
     * @return the value of lo_tutorial_order.cust_id
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_order.cust_id
     *
     * @param custId the value for lo_tutorial_order.cust_id
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setCustId(String custId) {
        this.custId = custId == null ? null : custId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_order.cust_name
     *
     * @return the value of lo_tutorial_order.cust_name
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_order.cust_name
     *
     * @param custName the value for lo_tutorial_order.cust_name
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_order.product_id
     *
     * @return the value of lo_tutorial_order.product_id
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_order.product_id
     *
     * @param productId the value for lo_tutorial_order.product_id
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_order.product_name
     *
     * @return the value of lo_tutorial_order.product_name
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_order.product_name
     *
     * @param productName the value for lo_tutorial_order.product_name
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_order.apply_amount
     *
     * @return the value of lo_tutorial_order.apply_amount
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public BigDecimal getApplyAmount() {
        return applyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_order.apply_amount
     *
     * @param applyAmount the value for lo_tutorial_order.apply_amount
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setApplyAmount(BigDecimal applyAmount) {
        this.applyAmount = applyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_order.apply_share
     *
     * @return the value of lo_tutorial_order.apply_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public BigDecimal getApplyShare() {
        return applyShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_order.apply_share
     *
     * @param applyShare the value for lo_tutorial_order.apply_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setApplyShare(BigDecimal applyShare) {
        this.applyShare = applyShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_order.confirm_amount
     *
     * @return the value of lo_tutorial_order.confirm_amount
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public BigDecimal getConfirmAmount() {
        return confirmAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_order.confirm_amount
     *
     * @param confirmAmount the value for lo_tutorial_order.confirm_amount
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setConfirmAmount(BigDecimal confirmAmount) {
        this.confirmAmount = confirmAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_order.confirm_share
     *
     * @return the value of lo_tutorial_order.confirm_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public BigDecimal getConfirmShare() {
        return confirmShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_order.confirm_share
     *
     * @param confirmShare the value for lo_tutorial_order.confirm_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setConfirmShare(BigDecimal confirmShare) {
        this.confirmShare = confirmShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_order.contract_no
     *
     * @return the value of lo_tutorial_order.contract_no
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_order.contract_no
     *
     * @param contractNo the value for lo_tutorial_order.contract_no
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo == null ? null : contractNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_order.order_status
     *
     * @return the value of lo_tutorial_order.order_status
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_order.order_status
     *
     * @param orderStatus the value for lo_tutorial_order.order_status
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_order.handle_status
     *
     * @return the value of lo_tutorial_order.handle_status
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getHandleStatus() {
        return handleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_order.handle_status
     *
     * @param handleStatus the value for lo_tutorial_order.handle_status
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setHandleStatus(String handleStatus) {
        this.handleStatus = handleStatus == null ? null : handleStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_order.ext_data
     *
     * @return the value of lo_tutorial_order.ext_data
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getExtData() {
        return extData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_order.ext_data
     *
     * @param extData the value for lo_tutorial_order.ext_data
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setExtData(String extData) {
        this.extData = extData == null ? null : extData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderNo=").append(orderNo);
        sb.append(", channel=").append(channel);
        sb.append(", channelDate=").append(channelDate);
        sb.append(", channelJnlNo=").append(channelJnlNo);
        sb.append(", productCode=").append(productCode);
        sb.append(", transAction=").append(transAction);
        sb.append(", custId=").append(custId);
        sb.append(", custName=").append(custName);
        sb.append(", productId=").append(productId);
        sb.append(", productName=").append(productName);
        sb.append(", applyAmount=").append(applyAmount);
        sb.append(", applyShare=").append(applyShare);
        sb.append(", confirmAmount=").append(confirmAmount);
        sb.append(", confirmShare=").append(confirmShare);
        sb.append(", contractNo=").append(contractNo);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", handleStatus=").append(handleStatus);
        sb.append(", extData=").append(extData);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}