package cn.openlo.tutorial.dto;

import cn.openlo.gear.dataobject.PersistentDTOSupport;
import java.io.Serializable;

public class LoTutorialCustShareKey extends PersistentDTOSupport implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_cust_share.cust_id
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private String custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_cust_share.product_id
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lo_tutorial_cust_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_cust_share.cust_id
     *
     * @return the value of lo_tutorial_cust_share.cust_id
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_cust_share.cust_id
     *
     * @param custId the value for lo_tutorial_cust_share.cust_id
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setCustId(String custId) {
        this.custId = custId == null ? null : custId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_cust_share.product_id
     *
     * @return the value of lo_tutorial_cust_share.product_id
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_cust_share.product_id
     *
     * @param productId the value for lo_tutorial_cust_share.product_id
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_cust_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", custId=").append(custId);
        sb.append(", productId=").append(productId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}