package cn.openlo.tutorial.dto;

import cn.openlo.datasource.executor.ShardingExample;
import cn.openlo.datasource.executor.ShardingTable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LoTutorialProductCriteria implements ShardingTable, ShardingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    protected List<Criteria> oredCriteria;

    protected Integer limit;

    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    protected String dbGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    protected String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    protected String tableIndex;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public LoTutorialProductCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return this.limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return this.offset;
    }

    public BoundBuilder boundBuilder() {
        return new BoundBuilder();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setDbGroup(String dbGroup) {
        this.dbGroup = dbGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getDbGroup() {
        return dbGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setTableIndex(String tableIndex) {
        this.tableIndex = tableIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getTableIndex() {
        return tableIndex;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(String value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(String value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(String value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(String value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(String value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLike(String value) {
            addCriterion("product_id like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotLike(String value) {
            addCriterion("product_id not like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<String> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<String> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(String value1, String value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(String value1, String value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andSingleMinSubIsNull() {
            addCriterion("single_min_sub is null");
            return (Criteria) this;
        }

        public Criteria andSingleMinSubIsNotNull() {
            addCriterion("single_min_sub is not null");
            return (Criteria) this;
        }

        public Criteria andSingleMinSubEqualTo(BigDecimal value) {
            addCriterion("single_min_sub =", value, "singleMinSub");
            return (Criteria) this;
        }

        public Criteria andSingleMinSubNotEqualTo(BigDecimal value) {
            addCriterion("single_min_sub <>", value, "singleMinSub");
            return (Criteria) this;
        }

        public Criteria andSingleMinSubGreaterThan(BigDecimal value) {
            addCriterion("single_min_sub >", value, "singleMinSub");
            return (Criteria) this;
        }

        public Criteria andSingleMinSubGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("single_min_sub >=", value, "singleMinSub");
            return (Criteria) this;
        }

        public Criteria andSingleMinSubLessThan(BigDecimal value) {
            addCriterion("single_min_sub <", value, "singleMinSub");
            return (Criteria) this;
        }

        public Criteria andSingleMinSubLessThanOrEqualTo(BigDecimal value) {
            addCriterion("single_min_sub <=", value, "singleMinSub");
            return (Criteria) this;
        }

        public Criteria andSingleMinSubIn(List<BigDecimal> values) {
            addCriterion("single_min_sub in", values, "singleMinSub");
            return (Criteria) this;
        }

        public Criteria andSingleMinSubNotIn(List<BigDecimal> values) {
            addCriterion("single_min_sub not in", values, "singleMinSub");
            return (Criteria) this;
        }

        public Criteria andSingleMinSubBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("single_min_sub between", value1, value2, "singleMinSub");
            return (Criteria) this;
        }

        public Criteria andSingleMinSubNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("single_min_sub not between", value1, value2, "singleMinSub");
            return (Criteria) this;
        }

        public Criteria andSingleMaxSubIsNull() {
            addCriterion("single_max_sub is null");
            return (Criteria) this;
        }

        public Criteria andSingleMaxSubIsNotNull() {
            addCriterion("single_max_sub is not null");
            return (Criteria) this;
        }

        public Criteria andSingleMaxSubEqualTo(BigDecimal value) {
            addCriterion("single_max_sub =", value, "singleMaxSub");
            return (Criteria) this;
        }

        public Criteria andSingleMaxSubNotEqualTo(BigDecimal value) {
            addCriterion("single_max_sub <>", value, "singleMaxSub");
            return (Criteria) this;
        }

        public Criteria andSingleMaxSubGreaterThan(BigDecimal value) {
            addCriterion("single_max_sub >", value, "singleMaxSub");
            return (Criteria) this;
        }

        public Criteria andSingleMaxSubGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("single_max_sub >=", value, "singleMaxSub");
            return (Criteria) this;
        }

        public Criteria andSingleMaxSubLessThan(BigDecimal value) {
            addCriterion("single_max_sub <", value, "singleMaxSub");
            return (Criteria) this;
        }

        public Criteria andSingleMaxSubLessThanOrEqualTo(BigDecimal value) {
            addCriterion("single_max_sub <=", value, "singleMaxSub");
            return (Criteria) this;
        }

        public Criteria andSingleMaxSubIn(List<BigDecimal> values) {
            addCriterion("single_max_sub in", values, "singleMaxSub");
            return (Criteria) this;
        }

        public Criteria andSingleMaxSubNotIn(List<BigDecimal> values) {
            addCriterion("single_max_sub not in", values, "singleMaxSub");
            return (Criteria) this;
        }

        public Criteria andSingleMaxSubBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("single_max_sub between", value1, value2, "singleMaxSub");
            return (Criteria) this;
        }

        public Criteria andSingleMaxSubNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("single_max_sub not between", value1, value2, "singleMaxSub");
            return (Criteria) this;
        }

        public Criteria andSingleSubAddUnitIsNull() {
            addCriterion("single_sub_add_unit is null");
            return (Criteria) this;
        }

        public Criteria andSingleSubAddUnitIsNotNull() {
            addCriterion("single_sub_add_unit is not null");
            return (Criteria) this;
        }

        public Criteria andSingleSubAddUnitEqualTo(BigDecimal value) {
            addCriterion("single_sub_add_unit =", value, "singleSubAddUnit");
            return (Criteria) this;
        }

        public Criteria andSingleSubAddUnitNotEqualTo(BigDecimal value) {
            addCriterion("single_sub_add_unit <>", value, "singleSubAddUnit");
            return (Criteria) this;
        }

        public Criteria andSingleSubAddUnitGreaterThan(BigDecimal value) {
            addCriterion("single_sub_add_unit >", value, "singleSubAddUnit");
            return (Criteria) this;
        }

        public Criteria andSingleSubAddUnitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("single_sub_add_unit >=", value, "singleSubAddUnit");
            return (Criteria) this;
        }

        public Criteria andSingleSubAddUnitLessThan(BigDecimal value) {
            addCriterion("single_sub_add_unit <", value, "singleSubAddUnit");
            return (Criteria) this;
        }

        public Criteria andSingleSubAddUnitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("single_sub_add_unit <=", value, "singleSubAddUnit");
            return (Criteria) this;
        }

        public Criteria andSingleSubAddUnitIn(List<BigDecimal> values) {
            addCriterion("single_sub_add_unit in", values, "singleSubAddUnit");
            return (Criteria) this;
        }

        public Criteria andSingleSubAddUnitNotIn(List<BigDecimal> values) {
            addCriterion("single_sub_add_unit not in", values, "singleSubAddUnit");
            return (Criteria) this;
        }

        public Criteria andSingleSubAddUnitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("single_sub_add_unit between", value1, value2, "singleSubAddUnit");
            return (Criteria) this;
        }

        public Criteria andSingleSubAddUnitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("single_sub_add_unit not between", value1, value2, "singleSubAddUnit");
            return (Criteria) this;
        }

        public Criteria andMaxUserLimitIsNull() {
            addCriterion("max_user_limit is null");
            return (Criteria) this;
        }

        public Criteria andMaxUserLimitIsNotNull() {
            addCriterion("max_user_limit is not null");
            return (Criteria) this;
        }

        public Criteria andMaxUserLimitEqualTo(BigDecimal value) {
            addCriterion("max_user_limit =", value, "maxUserLimit");
            return (Criteria) this;
        }

        public Criteria andMaxUserLimitNotEqualTo(BigDecimal value) {
            addCriterion("max_user_limit <>", value, "maxUserLimit");
            return (Criteria) this;
        }

        public Criteria andMaxUserLimitGreaterThan(BigDecimal value) {
            addCriterion("max_user_limit >", value, "maxUserLimit");
            return (Criteria) this;
        }

        public Criteria andMaxUserLimitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("max_user_limit >=", value, "maxUserLimit");
            return (Criteria) this;
        }

        public Criteria andMaxUserLimitLessThan(BigDecimal value) {
            addCriterion("max_user_limit <", value, "maxUserLimit");
            return (Criteria) this;
        }

        public Criteria andMaxUserLimitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("max_user_limit <=", value, "maxUserLimit");
            return (Criteria) this;
        }

        public Criteria andMaxUserLimitIn(List<BigDecimal> values) {
            addCriterion("max_user_limit in", values, "maxUserLimit");
            return (Criteria) this;
        }

        public Criteria andMaxUserLimitNotIn(List<BigDecimal> values) {
            addCriterion("max_user_limit not in", values, "maxUserLimit");
            return (Criteria) this;
        }

        public Criteria andMaxUserLimitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("max_user_limit between", value1, value2, "maxUserLimit");
            return (Criteria) this;
        }

        public Criteria andMaxUserLimitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("max_user_limit not between", value1, value2, "maxUserLimit");
            return (Criteria) this;
        }

        public Criteria andSellStatusIsNull() {
            addCriterion("sell_status is null");
            return (Criteria) this;
        }

        public Criteria andSellStatusIsNotNull() {
            addCriterion("sell_status is not null");
            return (Criteria) this;
        }

        public Criteria andSellStatusEqualTo(String value) {
            addCriterion("sell_status =", value, "sellStatus");
            return (Criteria) this;
        }

        public Criteria andSellStatusNotEqualTo(String value) {
            addCriterion("sell_status <>", value, "sellStatus");
            return (Criteria) this;
        }

        public Criteria andSellStatusGreaterThan(String value) {
            addCriterion("sell_status >", value, "sellStatus");
            return (Criteria) this;
        }

        public Criteria andSellStatusGreaterThanOrEqualTo(String value) {
            addCriterion("sell_status >=", value, "sellStatus");
            return (Criteria) this;
        }

        public Criteria andSellStatusLessThan(String value) {
            addCriterion("sell_status <", value, "sellStatus");
            return (Criteria) this;
        }

        public Criteria andSellStatusLessThanOrEqualTo(String value) {
            addCriterion("sell_status <=", value, "sellStatus");
            return (Criteria) this;
        }

        public Criteria andSellStatusLike(String value) {
            addCriterion("sell_status like", value, "sellStatus");
            return (Criteria) this;
        }

        public Criteria andSellStatusNotLike(String value) {
            addCriterion("sell_status not like", value, "sellStatus");
            return (Criteria) this;
        }

        public Criteria andSellStatusIn(List<String> values) {
            addCriterion("sell_status in", values, "sellStatus");
            return (Criteria) this;
        }

        public Criteria andSellStatusNotIn(List<String> values) {
            addCriterion("sell_status not in", values, "sellStatus");
            return (Criteria) this;
        }

        public Criteria andSellStatusBetween(String value1, String value2) {
            addCriterion("sell_status between", value1, value2, "sellStatus");
            return (Criteria) this;
        }

        public Criteria andSellStatusNotBetween(String value1, String value2) {
            addCriterion("sell_status not between", value1, value2, "sellStatus");
            return (Criteria) this;
        }

        public Criteria andExtDataIsNull() {
            addCriterion("ext_data is null");
            return (Criteria) this;
        }

        public Criteria andExtDataIsNotNull() {
            addCriterion("ext_data is not null");
            return (Criteria) this;
        }

        public Criteria andExtDataEqualTo(String value) {
            addCriterion("ext_data =", value, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataNotEqualTo(String value) {
            addCriterion("ext_data <>", value, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataGreaterThan(String value) {
            addCriterion("ext_data >", value, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataGreaterThanOrEqualTo(String value) {
            addCriterion("ext_data >=", value, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataLessThan(String value) {
            addCriterion("ext_data <", value, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataLessThanOrEqualTo(String value) {
            addCriterion("ext_data <=", value, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataLike(String value) {
            addCriterion("ext_data like", value, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataNotLike(String value) {
            addCriterion("ext_data not like", value, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataIn(List<String> values) {
            addCriterion("ext_data in", values, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataNotIn(List<String> values) {
            addCriterion("ext_data not in", values, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataBetween(String value1, String value2) {
            addCriterion("ext_data between", value1, value2, "extData");
            return (Criteria) this;
        }

        public Criteria andExtDataNotBetween(String value1, String value2) {
            addCriterion("ext_data not between", value1, value2, "extData");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("created_by like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("created_by not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andDateCreatedIsNull() {
            addCriterion("date_created is null");
            return (Criteria) this;
        }

        public Criteria andDateCreatedIsNotNull() {
            addCriterion("date_created is not null");
            return (Criteria) this;
        }

        public Criteria andDateCreatedEqualTo(Date value) {
            addCriterion("date_created =", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedNotEqualTo(Date value) {
            addCriterion("date_created <>", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedGreaterThan(Date value) {
            addCriterion("date_created >", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("date_created >=", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedLessThan(Date value) {
            addCriterion("date_created <", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedLessThanOrEqualTo(Date value) {
            addCriterion("date_created <=", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedIn(List<Date> values) {
            addCriterion("date_created in", values, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedNotIn(List<Date> values) {
            addCriterion("date_created not in", values, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedBetween(Date value1, Date value2) {
            addCriterion("date_created between", value1, value2, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedNotBetween(Date value1, Date value2) {
            addCriterion("date_created not between", value1, value2, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNull() {
            addCriterion("updated_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNotNull() {
            addCriterion("updated_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByEqualTo(String value) {
            addCriterion("updated_by =", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotEqualTo(String value) {
            addCriterion("updated_by <>", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThan(String value) {
            addCriterion("updated_by >", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThanOrEqualTo(String value) {
            addCriterion("updated_by >=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThan(String value) {
            addCriterion("updated_by <", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThanOrEqualTo(String value) {
            addCriterion("updated_by <=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLike(String value) {
            addCriterion("updated_by like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotLike(String value) {
            addCriterion("updated_by not like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIn(List<String> values) {
            addCriterion("updated_by in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotIn(List<String> values) {
            addCriterion("updated_by not in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByBetween(String value1, String value2) {
            addCriterion("updated_by between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotBetween(String value1, String value2) {
            addCriterion("updated_by not between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedIsNull() {
            addCriterion("date_updated is null");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedIsNotNull() {
            addCriterion("date_updated is not null");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedEqualTo(Date value) {
            addCriterion("date_updated =", value, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedNotEqualTo(Date value) {
            addCriterion("date_updated <>", value, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedGreaterThan(Date value) {
            addCriterion("date_updated >", value, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedGreaterThanOrEqualTo(Date value) {
            addCriterion("date_updated >=", value, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedLessThan(Date value) {
            addCriterion("date_updated <", value, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedLessThanOrEqualTo(Date value) {
            addCriterion("date_updated <=", value, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedIn(List<Date> values) {
            addCriterion("date_updated in", values, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedNotIn(List<Date> values) {
            addCriterion("date_updated not in", values, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedBetween(Date value1, Date value2) {
            addCriterion("date_updated between", value1, value2, "dateUpdated");
            return (Criteria) this;
        }

        public Criteria andDateUpdatedNotBetween(Date value1, Date value2) {
            addCriterion("date_updated not between", value1, value2, "dateUpdated");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public class BoundBuilder {
        protected Integer limit;

        protected Integer offset;

        public Integer limit() {
            return this.limit;
        }

        public BoundBuilder limit(Integer limit) {
            this.limit = limit;
            return this;
        }

        public Integer offset() {
            return this.offset;
        }

        public BoundBuilder offset(Integer offset) {
            this.offset = offset;
            return this;
        }

        public LoTutorialProductCriteria build() {
            LoTutorialProductCriteria.this.limit = limit;
            LoTutorialProductCriteria.this.offset = offset;
            return LoTutorialProductCriteria.this;
        }
    }
}