package cn.openlo.tutorial.dto;

import cn.openlo.gear.dataobject.PersistentDTOSupport;
import java.io.Serializable;
import java.math.BigDecimal;

public class LoTutorialProduct extends PersistentDTOSupport implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_product.product_id
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_product.product_name
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_product.single_min_sub
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private BigDecimal singleMinSub;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_product.single_max_sub
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private BigDecimal singleMaxSub;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_product.single_sub_add_unit
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private BigDecimal singleSubAddUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_product.max_user_limit
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private BigDecimal maxUserLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_product.sell_status
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private String sellStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lo_tutorial_product.ext_data
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private String extData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_product.product_id
     *
     * @return the value of lo_tutorial_product.product_id
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_product.product_id
     *
     * @param productId the value for lo_tutorial_product.product_id
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_product.product_name
     *
     * @return the value of lo_tutorial_product.product_name
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_product.product_name
     *
     * @param productName the value for lo_tutorial_product.product_name
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_product.single_min_sub
     *
     * @return the value of lo_tutorial_product.single_min_sub
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public BigDecimal getSingleMinSub() {
        return singleMinSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_product.single_min_sub
     *
     * @param singleMinSub the value for lo_tutorial_product.single_min_sub
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setSingleMinSub(BigDecimal singleMinSub) {
        this.singleMinSub = singleMinSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_product.single_max_sub
     *
     * @return the value of lo_tutorial_product.single_max_sub
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public BigDecimal getSingleMaxSub() {
        return singleMaxSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_product.single_max_sub
     *
     * @param singleMaxSub the value for lo_tutorial_product.single_max_sub
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setSingleMaxSub(BigDecimal singleMaxSub) {
        this.singleMaxSub = singleMaxSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_product.single_sub_add_unit
     *
     * @return the value of lo_tutorial_product.single_sub_add_unit
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public BigDecimal getSingleSubAddUnit() {
        return singleSubAddUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_product.single_sub_add_unit
     *
     * @param singleSubAddUnit the value for lo_tutorial_product.single_sub_add_unit
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setSingleSubAddUnit(BigDecimal singleSubAddUnit) {
        this.singleSubAddUnit = singleSubAddUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_product.max_user_limit
     *
     * @return the value of lo_tutorial_product.max_user_limit
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public BigDecimal getMaxUserLimit() {
        return maxUserLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_product.max_user_limit
     *
     * @param maxUserLimit the value for lo_tutorial_product.max_user_limit
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setMaxUserLimit(BigDecimal maxUserLimit) {
        this.maxUserLimit = maxUserLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_product.sell_status
     *
     * @return the value of lo_tutorial_product.sell_status
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getSellStatus() {
        return sellStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_product.sell_status
     *
     * @param sellStatus the value for lo_tutorial_product.sell_status
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setSellStatus(String sellStatus) {
        this.sellStatus = sellStatus == null ? null : sellStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lo_tutorial_product.ext_data
     *
     * @return the value of lo_tutorial_product.ext_data
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public String getExtData() {
        return extData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lo_tutorial_product.ext_data
     *
     * @param extData the value for lo_tutorial_product.ext_data
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    public void setExtData(String extData) {
        this.extData = extData == null ? null : extData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", productId=").append(productId);
        sb.append(", productName=").append(productName);
        sb.append(", singleMinSub=").append(singleMinSub);
        sb.append(", singleMaxSub=").append(singleMaxSub);
        sb.append(", singleSubAddUnit=").append(singleSubAddUnit);
        sb.append(", maxUserLimit=").append(maxUserLimit);
        sb.append(", sellStatus=").append(sellStatus);
        sb.append(", extData=").append(extData);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}