package cn.openlo.tutorial.dao.mybatis;

import cn.openlo.dataobject.DAO;
import cn.openlo.tutorial.dto.LoTutorialProduct;
import cn.openlo.tutorial.dto.LoTutorialProductCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoTutorialProductMapper extends DAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int countByExample(LoTutorialProductCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int deleteByExample(LoTutorialProductCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int deleteByPrimaryKey(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int insert(LoTutorialProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int insertSelective(LoTutorialProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    List<LoTutorialProduct> selectByExample(LoTutorialProductCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    LoTutorialProduct selectByPrimaryKey(String productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") LoTutorialProduct record, @Param("example") LoTutorialProductCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int updateByExample(@Param("record") LoTutorialProduct record, @Param("example") LoTutorialProductCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(LoTutorialProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_product
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int updateByPrimaryKey(LoTutorialProduct record);
}