package cn.openlo.tutorial.dao.mybatis;

import cn.openlo.dataobject.DAO;
import cn.openlo.tutorial.dto.LoTutorialOrder;
import cn.openlo.tutorial.dto.LoTutorialOrderCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoTutorialOrderMapper extends DAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int countByExample(LoTutorialOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int deleteByExample(LoTutorialOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int deleteByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int insert(LoTutorialOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int insertSelective(LoTutorialOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    List<LoTutorialOrder> selectByExample(LoTutorialOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    LoTutorialOrder selectByPrimaryKey(String orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") LoTutorialOrder record, @Param("example") LoTutorialOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int updateByExample(@Param("record") LoTutorialOrder record, @Param("example") LoTutorialOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(LoTutorialOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_order
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int updateByPrimaryKey(LoTutorialOrder record);
}