package cn.openlo.tutorial.dao.mybatis;

import cn.openlo.dataobject.DAO;
import cn.openlo.tutorial.dto.LoTutorialCustShare;
import cn.openlo.tutorial.dto.LoTutorialCustShareCriteria;
import cn.openlo.tutorial.dto.LoTutorialCustShareKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoTutorialCustShareMapper extends DAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_cust_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int countByExample(LoTutorialCustShareCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_cust_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int deleteByExample(LoTutorialCustShareCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_cust_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int deleteByPrimaryKey(LoTutorialCustShareKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_cust_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int insert(LoTutorialCustShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_cust_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int insertSelective(LoTutorialCustShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_cust_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    List<LoTutorialCustShare> selectByExample(LoTutorialCustShareCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_cust_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    LoTutorialCustShare selectByPrimaryKey(LoTutorialCustShareKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_cust_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") LoTutorialCustShare record, @Param("example") LoTutorialCustShareCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_cust_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int updateByExample(@Param("record") LoTutorialCustShare record, @Param("example") LoTutorialCustShareCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_cust_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(LoTutorialCustShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lo_tutorial_cust_share
     *
     * @mbggenerated Sat Apr 28 16:18:03 GMT+08:00 2018
     */
    int updateByPrimaryKey(LoTutorialCustShare record);
}